### PR TITLE
fix(404): redirect to home page if page not found

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

Currently if page is not found, a blank screen appears. Instead we could display a error 404 page and provide option to go back to home page. 

### Changes

Display page not found page and provide link to home page

## Screenshot

image

## How to test

Visit a random non-existing url

### CODE REVIEW

**Comment by Shruti3004** [comment]
@Aman-Codes should we make 404 page and there we can give the link like default page or should we do this, what's your call on this?

**Comment by Aman-Codes** [comment]
Yes we can create a custom 404 page as well. **Mentors** can share their opinion on whether to redirect or create a 404 page

**Comment by GMishx** [comment]
Currently FOSSology shows following message in case of 404 or 403 (logged out)
```
Module unavailable or your login session timed out.

Click here to continue.
```

Clicking on the link takes you to the login page (which will be home page) and upon successful login redirects back to where you were (only if it was 403).

So we can also show a separate error page with link to home and later work on redirects.

funny

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
Please change with a better font :pray: 
image

**Comment by Aman-Codes** [comment]
@GMishx 
Yes surely. Which font are you using in the above image?

**Comment by GMishx** [comment]
> @GMishx
> Yes surely. Which font are you using in the above image?

I am not sure, it's called Z003 apparently 
image

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
