### PR TITLE
feat(active-navbar): added the active class to nav items

### PR DESCRIPTION
**Pull request by Shruti3004**
## Description

Added the active class to nav-items and changed the dropdown item colour to the theme primary colour instead of bootstrap primary colour.

## Changes

- Added the secondary colour to the theme.js for the darker shade of active element.
- Added the `active-nav-item` and `dropdown-item:hover` in the globalStyle.js
- Added the location for the paths in header component.
- Added the `import-parse` property in .eslintrc to resolve the parsing errors.
- Fixed the groups api function by removing credentials which is defined in sendRequest.

## Screenshots
Screenshot from 2021-07-19 13-35-32
Screenshot from 2021-07-19 13-35-40

### CODE REVIEW

**Comment by Shruti3004** [comment]
@GMishx Should I add this active class to dropdwon items as well?

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
> @GMishx Should I add this active class to dropdwon items as well?

In case of dropdown items, it will nice to have the highlight at least on the parent item. Like if I am on "Organize > Uploads > Delete uploaded files", if Organize is highlighted, it should be enough for now.

**Comment by shaheemazmalmmd** [comment]
Can we have a just a underline to highlight active page ? 

* "keep the current CSS for for hover "
* "Add the underlined fonts for active pages".

**Comment by Shruti3004** [comment]
> Can we have a just a underline to highlight active page ?
> 
> * "keep the current CSS for for hover "
> * "Add the underlined fonts for active pages".

Yes sure @shaheemazmalmmd

**Comment by GMishx** [comment]
Hover is increasing the button width
image
image

snap

Other than that every thing looks good :+1:

**Comment by Shruti3004** [comment]
> Hover is increasing the button width
> image
> image
> 
> snap
> 
> Other than that every thing looks good

Screenshot from 2021-07-22 18-44-02
instead of padding i have replaced it with margin.

**Comment by GMishx** [comment]
It's because of the font-weight actually but not very critical.

**Review by GMishx — APPROVED** [review]
Changes looks good. Tested, working as expected.

**Comment by Shruti3004** [comment]
@GMishx resolved the merge conflicts.

**Pull request merged**
