### PR TITLE
feat(linter): add airbnb style guide

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

Added the airbnb style guide (as suggested by @sjha2048) and updated eslint config.

### Changes

- Added `eslint-config-airbnb`
- Manually resolved over 200 errors and warnings due to updated style guide
- Added missing license header to files

## How to test

Check all pages are working

### CODE REVIEW

**Review by sjha2048 — APPROVED** [review]

**Comment by GMishx** [comment]
Great thing @Aman-Codes and @sjha2048 . Let's merge it after every open PR otherwise they will become invalid.

**Comment by GMishx** [comment]
I think every other branch is merged. @Aman-Codes can you please rebase the branch?
We can merge this as soon as #96 is merged.

**Comment by shaheemazmalmmd** [comment]
@Aman-Codes Can you please resolve the conflicts ??

**Comment by Aman-Codes** [comment]
@GMishx @shaheemazmalmmd
Finally resolved all the merged conflicts. Please have a look

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by shaheemazmalmmd — APPROVED** [review]
Code looks good.

**Pull request merged**
