### PR TITLE
feature(ui): ui and styling for the `edit user page`

### LINKED ISSUE #231: (UI) Creation of the `Edit User Account` Page
### Description

The `edit user account` page is not implemented in the current ui as of now. I'd like to work on this.
cc : @GMishx @sjha2048 @shaheemazmalmmd

### PR DESCRIPTION
**Pull request by krishna9304**
## Description

Ui and API Implementation of the `Edit user page`. 

### Changes
Added all the UI components for the Edit user page and wrote frontend logic for data collection and better UX.

## Implementation demo
https://user-images.githubusercontent.com/71918441/184528131-2ff0e6bd-ab48-43fc-99d1-6a9d7c036268.mp4

## How to test
Go to `Admin > Users > Edit User Account` to see the new UI
1. For testing changes related to modifying user details, you need to install changes from this PR 👉 : https://github.com/fossology/fossology/pull/2262
2. For testing the token apis, you need to install changes from this PR 👉 : https://github.com/fossology/fossology/pull/2266

PTAL : @Shruti3004 @GMishx @shaheemazmalmmd @sjha2048 

This closes #231 .

### CODE REVIEW

**Comment by krishna9304** [comment]
PTAL : @GMishx @Shruti3004 @sjha2048

**Comment by krishna9304** [comment]
@GMishx @Shruti3004 PTAL at the recent changes, API implementation for this page is done.
1. For testing changes related to modifying user details, you need to install changes from this PR 👉 : https://github.com/fossology/fossology/pull/2262
2. For testing the token apis, you need to install changes from this PR 👉 : https://github.com/fossology/fossology/pull/2266

**Comment by shaheemazmalmmd** [comment]
@krishna9304 Can you rebase the branch and fix the merge conflicts ??

**Review by shaheemazmalmmd — APPROVED** [review]
Tested works as expected.

**Comment by krishna9304** [comment]
> @krishna9304 Can you rebase the branch and fix the merge conflicts ??

Yes, Done @shaheemazmalmmd .

**Pull request merged**
