### PR TITLE
feat(fossology-version): use fossology version from info API

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

Use fossology version from info API. Currently using `toLocaleString()` for build date and commit date.

### Changes

use fossology version from info API

## Screenshots
image

## How to test

See footer of any page

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
Please cache the `info` response in local storage at every login like user info to remove redundant calls to `/info` endpoint.

**Comment by Aman-Codes** [comment]
@GMishx 
Earlier whenever the user switches between public, private, or an admin layout-based component a request to info API was made. Fixed it now to ensure that only 1 API call is made during a user session.

**Now should we still save the version info in local storage?**
**Pros:**
- No further request to info API will be made if it's opened on a new tab or a window.

**Cons:**
- Version information will never be deleted from local storage as it is required even after logout.
- As a consequence, a user would have to manually delete the API version information from local storage to reflect changes in UI

**Comment by GMishx** [comment]
> @GMishx
> Earlier whenever the user switches between public, private, or an admin layout-based component a request to info API was made. Fixed it now to ensure that only 1 API call is made during a user session.
> 
> **Now should we still save the version info in local storage?**

It just needs to be cached for the session and can reside anywhere. Once the user loggsout, it gets deleted or when it loggin, it is recreated by calling API.

> **Pros:**
> 
>     * No further request to info API will be made if it's opened on a new tab or a window.
> 
> **Cons:**
> 
>     * Version information will never be deleted from local storage as it is required even after logout.

That should not happen. It should be deleted.

>     * As a consequence, a user would have to manually delete the API version information from local storage to reflect changes in UI

It should be fixed by deleting once user logout.

**Comment by Aman-Codes** [comment]
> It just needs to be cached for the session and can reside anywhere. Once the user loggsout, it gets deleted or when it loggin, it is recreated by calling API.

Hi @GMishx, In this case what should we display in footer after the user logs out and we delete the version information as you mentioned?
Also, the version information is needed to be displayed in the footer of pages that can be accessed without login like the help and about page.

**Comment by GMishx** [comment]
> Hi @GMishx, In this case what should we display in footer after the user logs out and we delete the version information as you mentioned?

Ah ha, I missed that point. I just wanted some caching to be there.
One thing can be done is to create a session cookie and store the version information there. And at first load or first call to get the version info from cookie, if it does not exists, the API call can be done.
Doing so, the storage will be same for each user irrespective of them being logged in or not. And as soon as they close the browser, the cookie will be destroyed so no custom deletion will be required.

> Also, the version information is needed to be displayed in the footer of pages that can be accessed without login like the help and about page.

I think the above mentioned point should cover it. What do you think about it?

**Comment by Aman-Codes** [comment]
> I think the above mentioned point should cover it. What do you think about it?

Yes sounds good. Updated the code to use session storage.

**Pull request merged**
