### PR TITLE
feat(url): added the upload from url page

### PR DESCRIPTION
**Pull request by Shruti3004**
## Description

Added the upload from url page.

## How to test

Visit to `/upload/url`

## Screenshots
Screenshot from 2021-07-25 14-38-25
Screenshot from 2021-07-25 14-38-09

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
While testing, I was able to upload the file but I could not change the state of any checkboxes. As a result, I could not schedule any agent on the upload. Please check once.

**Comment by Shruti3004** [comment]
> While testing, I was able to upload the file but I could not change the state of any checkboxes. As a result, I could not schedule any agent on the upload. Please check once.

@GMishx fixed that.

**Comment by GMishx** [comment]
Looks like the id for "Visible for all groups" and "Make Public" are same causing click on Make Public label to select the protected value.
image

**Comment by Shruti3004** [comment]
> Looks like the id for "Visible for all groups" and "Make Public" are same causing click on Make Public label to select the protected value.
> image

@GMishx fixed all the duplicate ids

**Review by GMishx — APPROVED** [review]

**Pull request merged**
