### PR TITLE
Dark mode delay Fixed #253

### LINKED ISSUE #253: Improvement : Dark Mode Switch Delay
### Description

When we are switching from dark mode to light mode and vice versa then the delay is different for the background and for the cards which seems asymmetric on the website and fixing it will enhance the UI.

#### How to reproduce

- Go to [FossologyUI Page](https://fossology.github.io/FOSSologyUI/)
- Scroll to Bottom
- Repeatedly Switch to DarkMode/Light Mode

Describe the bug and list the steps you used when the issue occurred.

[screen-capture (4).webm](https://user-images.githubusercontent.com/71088429/185855985-3378e0b7-acaf-4d9b-9f8a-1ef1ebd46798.webm)

You Can Notice in the Video that the three cards have more delay than the background.

### Versions

* Last commit id on master: 133c1af9942fd7ffd356b8ab2ff7b6edb70f7839
* OS :  Windows 10
* Browser: Chrome

### PR DESCRIPTION
**Pull request by RamGoel**
### Changes

Matched delay of Body with delay of Cards in Home Page #253

### CODE REVIEW

**Comment by RamGoel** [comment]
> ### Changes
> Matched delay of Body with delay of Cards in Home Page #253

@GMishx Have a Look

**Comment by shaheemazmalmmd** [comment]
@RamGoel Thank you for your contribution. can you please squash your commits to one ?

**Comment by RamGoel** [comment]
@shaheemazmalmmd Done , Looking forward to future contributions 🚀

**Comment by shaheemazmalmmd** [comment]
@RamGoel can you please fix the code style. you can run `npx prettier --write .` to fix it automatically.

**Pull request merged**
