### PR TITLE
feat(folder-navigation): add folder tree view

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

Added folder navigation tree view 

### Changes

- Added unlink upload or folder

## Screenshot

image

## How to test

Go to `http://localhost:3000/browse`

### CODE REVIEW

**Comment by GMishx** [comment]
Seeing the results I can truly say nice work
image

Just couple of suggestions:
1. Do not show the collapse chevron in case the node does not have any child.
2. Collapsing child sometimes distort the listing.

For reference, this is the plugin currently used by FOSSology: https://github.com/jzaefferer/jquery-treeview

**Comment by Aman-Codes** [comment]
> 1. Do not show the collapse chevron in case the node does not have any child.
> 2. Collapsing child sometimes distort the listing.

@GMishx  After hiding chevron for last child it looks like this

## Image 1
image
## Image 2
image


Then it might be difficult to tell that the `Fossology` folder belongs to which level in the fully expanded list.
And for the point 2, currently when a user clicks on any folder which does not have any child then it would toggle(opening/closing) its parent list.

**Comment by Aman-Codes** [comment]
@GMishx Updated this PR to use `react-virtualized-tree` and `array-to-tree` library.
Recreated the same UI as proposed earlier using these libraries.

image

**Review by GMishx — APPROVED** [review]
Changes looks good. Tested, working as expected.

**Comment by GMishx** [comment]
Now the tree looks extremely stable. Just one request, when the page first loads, the tree was collapsed for me. Can it be changed to expanded? @Aman-Codes

**Comment by Aman-Codes** [comment]
@GMishx Made the folder list fully expanded on initial load

**Pull request merged**
