### PR TITLE
feat(alert): alert message on homepage for logout error

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

In case of a 403 error, displayed the body of the response as a snack bar on the homepage. 
Previous discussion on #117 

### Changes

- Updated logout function to accept error message as a parameter
- Updated home page to display the error message from URL query parameter

## Screenshot
image

## How to test

Go to `http://localhost:3000/?message=Requested%20resource%20is%20forbidden`
Or make a request which returns a 403 error code.

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
Is it possible to remove the message from URL once snackbar is loaded?

image

**Comment by Aman-Codes** [comment]
> Is it possible to remove the message from URL once snackbar is loaded?

Yes, updated it to remove message after page load

**Review by GMishx — COMMENTED** [review]
Tested, working fine.

**Review by GMishx — APPROVED** [review]
Tested, working fine.

**Pull request merged**
