### PR TITLE
feat(integration): Integrated the fossology maintenance page.

### PR DESCRIPTION
**Pull request by dushimsam**
## Description
Integrated the Fossology maintenance page to the REST API in charge of activating the maintenance operations on the backend.

### Changes

1. Added API call functions and services and linked them to the endpoint.
2. Designed the functions to prepare the user request suitable for the API.

## How to test
1. Run `npm start` at the project's diretory.
2. Visit `/admin/mantainance`.
3. Select operations of your choice.
4. Press `submit` button

## Example

https://user-images.githubusercontent.com/66276301/184678066-360fc503-8dd6-4746-8848-68f90f31d615.mp4

### CODE REVIEW

**Comment by shaheemazmalmmd** [comment]
@dushimsam Please fix the testcases.

**Comment by dushimsam** [comment]
> This pull request has conflicts, please rebase to resolve those before we can evaluate the pull request.

resolved conflicts

**Comment by shaheemazmalmmd** [comment]
Tested the branch was not able to schedule the maintenance agent. Please check.
screenShot49

**Comment by dushimsam** [comment]
> Tested the branch was not able to schedule the maintenance agent. Please check. screenShot49

sorry issue fixed now.

**Comment by shaheemazmalmmd** [comment]
@dushimsam : branch is working fine. A suggestion ?

* You can uncheck the selected checkboxes if the agent schedule is successful.
* In case of agent/schedule failure you can keep the checkboxes checked.

**Comment by dushimsam** [comment]
> @dushimsam : branch is working fine. A suggestion ?
> 
> * You can uncheck the selected checkboxes if the agent schedule is successful.
> * In case of agent/schedule failure you can keep the checkboxes checked.

on it sir

**Comment by dushimsam** [comment]
Everything working perfectly sir , would you check again.

**Pull request merged**
