### PR TITLE
feat(UI): add more pages in UI

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

Add more UI pages

### Changes

- Added folder navigation
- Replace bootstrap alerts with snack bars
- Added upload VCS page
- Fix header on small screen
- Use agent preference from local storage
- Added pagination on browse page
- Added Prettier check to GitHub actions
- Added Schedule Analysis page
- Added admin layout
- Added edit upload page
- Added delete user page
- Added delete user page
- Added create group page
- Added upload move page
- Added folder unlink page
- Added move upload or copy upload page
- Added unlink upload or folder page
- Added delete upload page
- Logout user when token is revoked
- Updated alerts to snack bars
- Remove redundancy of credentials
- Added one shot analysis page
- Added one shot monk page
- Added delete upload page
- Fix heading and open external link in new tab
- Updated tooltip
- Fixed search, overview and create folder page
- Added custom alert
- Added routes for all pages

## How to test

Test all the pages

### CODE REVIEW

**Comment by sjha2048** [comment]
Looks good to me, only larger components need to be split into smaller components for readibiliy, will do another round of testing soon.

**Comment by GMishx** [comment]
> Looks good to me, only larger components need to be split into smaller components for readibiliy, will do another round of testing soon.

@sjha2048 , can you please create a new issue for this and merge the branch if the tests are successful for you?

**Review by GMishx — APPROVED** [review]

**Comment by sjha2048** [comment]
Will merge this by evening.

**Review by shaheemazmalmmd — APPROVED** [review]
Code looks Good. Needs Test

**Pull request merged**
