### PR TITLE
feat(group): add create group page

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

Added create group page

### Changes

- Added create group page
- Updated Header to display Admin section in Navbar only for admin users

## Screenshots
image

## How to test

Go to `http://localhost:3000/admin/groups/create`

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good. Tested, working as expected.

**Comment by GMishx** [comment]
Just one expected behavior. If I am not an admin, I can not see the page in nav bar, but I can directly access via link http://localhost:3000/admin/group/create
Can be solved in another issue for all admin related pages.

**Comment by Aman-Codes** [comment]
> Just one expected behavior. If I am not an admin, I can not see the page in nav bar, but I can directly access via link http://localhost:3000/admin/group/create
> Can be solved in another issue for all admin related pages.

@GMishx Rebased this PR. Will create a new layout component for admin pages in a separate PR

**Comment by GMishx** [comment]
There is one more conflict :upside_down_face:

**Pull request merged**
