### PR TITLE
Added lazy loading components

### LINKED ISSUE #160: Use lazy loading components
### Description

Currently all the components are loaded during initial page load which increases the initial load time. We could use [lazy loading](https://blog.logrocket.com/lazy-loading-components-in-react-16-6-6cea535c0b52/) to optimize the load time. 

#### Steps followed and expected result

Update imports to use lazy loading. Example change
```jsx
import Home from "./Home";
```
to
```jsx
const Home = React.lazy(() => import("./Home"));
```

### PR DESCRIPTION
**Pull request by soham4abc**
Signed-off-by: Soham Banerjee <sohambanerjee4abc@hotmail.com>

## Description

Added Lazy loading imports to the `Routes.jsx` file

### Changes

Files changed : `src/Routes.jsx`

Fixes #160

### CODE REVIEW

**Comment by soham4abc** [comment]
Formatted the file as per requirement!
PTAL @GMishx

**Comment by soham4abc** [comment]
I am working on the error give me 10 mins

**Comment by soham4abc** [comment]
image
Fixed PTAL @GMishx

**Comment by soham4abc** [comment]
image
Fixed! PTAL @GMishx

**Comment by soham4abc** [comment]
If the test fails again pls do let me know what exact changes I need to do

**Comment by GMishx** [comment]
@Aman-Codes @Shruti3004 @sjha2048 can you please help with the test cases.

Because of lazy loading, the snapshot is loaded as just
```html
<div>
  Loading... 
</div>
```

**Comment by Aman-Codes** [comment]
@soham4abc You had to update the test to take snapshot according to lazy loading.
Now, I have added that myself in this PR itself. 

So @GMishx its good to merge now

**Comment by soham4abc** [comment]
> @soham4abc You had to update the test to take snapshot according to lazy loading.
> Now, I have added that myself in this PR itself. 
> 
> So @GMishx its good to merge now

Thank you for your help!

**Review by GMishx — APPROVED** [review]
Changes looks good. Needs testing.

**Comment by GMishx** [comment]
@soham4abc , can you please squash your commits and format them according to [contributing guidelines](https://github.com/fossology/FOSSologyUI/blob/main/CONTRIBUTING.md#git-commit-conventions)?

You can do so by rebasing the branch with `main` and preserve the commit from Aman

**Comment by soham4abc** [comment]
> @soham4abc , can you please squash your commits and format them according to [contributing guidelines](https://github.com/fossology/FOSSologyUI/blob/main/CONTRIBUTING.md#git-commit-conventions)?
> 
> You can do so by rebasing the branch with `main` and preserve the commit from Aman

PTAL

**Comment by GMishx** [comment]
Oh, there is one additional commit in this PR now. I think it is 546f10f6a9ba7b8cdec867f11b4d4746005bf385

**Comment by soham4abc** [comment]
> Oh, there is one additional commit in this PR now. I think it is [546f10f](https://github.com/fossology/FOSSologyUI/commit/546f10f6a9ba7b8cdec867f11b4d4746005bf385)

Should it stay or should I remove it.. It was fetched from the rebase

**Comment by Shruti3004** [comment]
> 

Hey @soham4abc you can squash your commits.

**Comment by Shruti3004** [comment]
Hey @soham4abc how did you rebased your branch, you are missing something!

**Comment by soham4abc** [comment]
> Hey @soham4abc how did you rebased your branch, you are missing something!

I am on it I messed up... will fix this asap

**Comment by Shruti3004** [comment]
> > Hey @soham4abc how did you rebased your branch, you are missing something!
> 
> I am on it I messed up... will fix this asap

No worries, it happens. Take your time.
Though if something major happened you can use `git reflog` command to reverse it back.

**Comment by soham4abc** [comment]
> > > Hey @soham4abc how did you rebased your branch, you are missing something!
> > 
> > 
> > I am on it I messed up... will fix this asap
> 
> No worries, it happens. Take your time. Though if something major happened you can use `git reflog` command to reverse it back.

All issues fixed and commit history cleaned and commits squashed! Please do have a look and let me know if any more changes are required or not! @GMishx @Shruti3004

**Comment by GMishx** [comment]
Hey @soham4abc , looks like something got messed-up in the Routes.jsx file while rebasing. There are two imports for each page now.

Please fix and amend the commit

**Comment by soham4abc** [comment]
> Hey @soham4abc , looks like something got messed-up in the Routes.jsx file while rebasing. There are two imports for each page now.
> 
> Please fix and amend the commit

I discovered it.. on it give me 10 minutes

**Comment by soham4abc** [comment]
@GMishx  can you please re run the tests.

**Comment by GMishx** [comment]
I am getting following warnings whenever I load a page. Is it related to this PR?

```
Warning: Failed prop type: Invalid prop `component` supplied to `PrivateLayout`.
PrivateLayout@http://localhost:3000/static/js/57.chunk.js:56:23
C@http://localhost:3000/static/js/vendors~main.chunk.js:36038:31
Switch@http://localhost:3000/static/js/vendors~main.chunk.js:35983:29
Router@http://localhost:3000/static/js/vendors~main.chunk.js:35416:30
BrowserRouter@http://localhost:3000/static/js/vendors~main.chunk.js:35036:35
Routes
Ge@http://localhost:3000/static/js/vendors~main.chunk.js:42047:67
GlobalProvider@http://localhost:3000/static/js/main.chunk.js:1167:24
App@http://localhost:3000/static/js/main.chunk.js:111:63
Suspense index.js:1
```

```
Warning: Failed prop type: Invalid prop `component` supplied to `AdminLayout`.
AdminLayout@http://localhost:3000/static/js/56.chunk.js:56:21
C@http://localhost:3000/static/js/vendors~main.chunk.js:36038:31
Switch@http://localhost:3000/static/js/vendors~main.chunk.js:35983:29
Router@http://localhost:3000/static/js/vendors~main.chunk.js:35416:30
BrowserRouter@http://localhost:3000/static/js/vendors~main.chunk.js:35036:35
Routes
Ge@http://localhost:3000/static/js/vendors~main.chunk.js:42047:67
GlobalProvider@http://localhost:3000/static/js/main.chunk.js:1167:24
App@http://localhost:3000/static/js/main.chunk.js:111:63
Suspense index.js:1
```

**Comment by soham4abc** [comment]
> Failed prop type: Invalid prop `component` supplied to

https://stackoverflow.com/questions/33950433/warning-failed-proptype-invalid-prop-component-supplied-to-route?rq=1

This might help

**Comment by GMishx** [comment]
I am not good with JS. With my limited knowledge and from stackoverflow link, I understood that since the components are now lazy loaded, thus while adding them to `Routes` they are not available??

Because all the components use `export default Component` syntax rather than `module.exports = Component` as suggested in answers.

@Aman-Codes @Shruti3004 @sjha2048

**Comment by Aman-Codes** [comment]
https://github.com/fossology/FOSSologyUI/blob/a7386bb909b57dac2e1123bb51291aaa1c097e31/src/shared/PublicLayout.jsx#L42-L42

https://github.com/fossology/FOSSologyUI/blob/a7386bb909b57dac2e1123bb51291aaa1c097e31/src/shared/PrivateLayout.jsx#L55-L55

https://github.com/fossology/FOSSologyUI/blob/a7386bb909b57dac2e1123bb51291aaa1c097e31/src/shared/AdminLayout.jsx#L55-L55

Hi @soham4abc Could you please replace the above 3 line with the below line. It will fix the error faced by @GMishx 

```jsx
  component: PropTypes.oneOfType([PropTypes.element, PropTypes.elementType]),
```

**Comment by soham4abc** [comment]
The warnings are removed. Please continue testing @GMishx  @Aman-Codes

**Review by GMishx — APPROVED** [review]
Working as expected.

**Comment by soham4abc** [comment]
Sorry... This PR should have been much smoother. Sorry to bother you all! And thanks for your help @GMishx @Aman-Codes @Shruti3004

**Pull request merged**
