### PR TITLE
feat(layout): add admin layout for admin pages

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

Added admin layout component

### Changes

- Created a new auth gaurd for admin pages which checks whether the user is admin or not. If not it redirects to homepage.

### CODE REVIEW

**Comment by GMishx** [comment]
Can it be merged now @Aman-Codes ?

**Comment by Aman-Codes** [comment]
> Can it be merged now @Aman-Codes ?

@GMishx Yes surely!

**Comment by GMishx** [comment]
I can still load the page from non-admin user
image

**Review by GMishx — APPROVED** [review]

**Comment by GMishx** [comment]
Good now @Aman-Codes ?

**Comment by Aman-Codes** [comment]
Yes tested it is working now

**Pull request merged**
