### PR TITLE
feat(tooltip): added the extra information

### PR DESCRIPTION
**Pull request by Shruti3004**
## Description

Added the additional information for the components.

## Screenshots
Screenshot from 2021-07-02 07-26-53

Screenshot from 2021-07-03 11-49-00

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
Tooltips are not visible in dark theme. Please check. Also, there is a stray `-` under "Ignore SCM.." checkbox.

image

**Comment by Shruti3004** [comment]
@GMishx updated

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
