### PR TITLE
refactor(handleError): add reusable function for error handling

### PR DESCRIPTION
**Pull request by Aman-Codes**
## Description

Reduced duplicate code by using reusable function.

### Changes

- Added reusable function for error handling
- Fixed eslint warnings in copyright script 

## How to test

Go to `localhost:3000`

### CODE REVIEW

**Comment by GMishx** [comment]
To me, every `handleError()` looks same. So won't it be better to move it in a common library and import from there?

**Comment by Aman-Codes** [comment]
@GMishx Updated it to use a shared handleError component

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
