### PR TITLE
feat(browse): Added the prototype for the uploads page

### PR DESCRIPTION
**Pull request by Shruti3004**
## Description

Added the Browse page prototype.

### Changes

- Added the api for browse page.
- Created the layout for the browse page.

## How to test

Visit to `/browse`

## Screenshots

Screenshot from 2021-07-01 07-14-51

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — APPROVED** [review]
Tested, working fine.

**Comment by GMishx** [comment]
Just one suggestion, I am not sure what are your plans, but the `recursive` can be set to false to fetch uploads only for the current folder.

And pagination is currently not working right?

**Comment by GMishx** [comment]
And just to let you know, the filter PR is also ready: https://github.com/fossology/fossology/pull/2038

**Comment by Shruti3004** [comment]
> Just one suggestion, I am not sure what are your plans, but the `recursive` can be set to false to fetch uploads only for the current folder.
> 
> And pagination is currently not working right?

Yes @GMishx, working on it, Actually we decided to divide our pr into chunks.

**Comment by Shruti3004** [comment]
> And just to let you know, the filter PR is also ready: [fossology/fossology#2038](https://github.com/fossology/fossology/pull/2038)

Ohh, great but I have checked it is not been merged yet as soon as it get merged we will work on that.

**Comment by Shruti3004** [comment]
@GMishx Resolved the merge conflicts

**Pull request merged**
